import type { PluginKindDefinition, PluginMetricsDef } from "./shared";
import {
  executorRef,
  executorReferenceArrayItem,
  inputArrayItem,
  nftSetTargetFields,
  stringArrayField,
} from "./shared";

export const executorPluginDefinitions: PluginKindDefinition[] = [
  {
    kind: "sequence",
    type: "executor",
    name: "Sequence",
    description: "按顺序编排 matcher 与 executor，是最常用入口执行器",
    icon: "GitBranch",
    configSchema: [
      {
        key: "args",
        description: "定义 sequence 的规则链。",
        label: "规则链",
        type: "array",
        required: true,
        example: "$cache_main\nmatches: !$has_resp, exec: $forward_main",
        item: {
          type: "object",
          label: "规则",
          summaryFields: ["exec"],
          fields: [
            {
              key: "matches",
              description: "定义当前规则的匹配条件。",
              label: "匹配条件",
              type: "array",
              example: "$has_resp\nqname domain:example.com\n!$blocked",
              itemOptions: [
                {
                  optionKey: "matcher_ref",
                  type: "reference",
                  label: "引用 matcher",
                  referenceTypes: ["matcher"],
                  referencePrefix: "$",
                  allowInvert: true,
                  example: "has_resp",
                },
                {
                  optionKey: "input",
                  type: "text",
                  label: "输入值",
                  example: "qname domain:example.com",
                },
              ],
            },
            {
              key: "exec",
              description:
                "定义规则命中后要执行的动作，可引用执行器或使用 accept、return、reject、jump、goto、mark、set_mark 等内置动作；mark 追加标记，set_mark 完整替换标记集合；reject 支持大小写不敏感的 RCODE 名称和数字。",
              label: "执行动作",
              type: "text",
              example:
                "$forward_main / accept / reject SERVFAIL / mark 1,2 / set_mark 2,3 / jump seq_tag",
            },
          ],
        },
      },
    ],
  },
  {
    kind: "forward",
    type: "executor",
    name: "Forward",
    description: "向一个或多个上游 DNS 发起查询",
    icon: "ArrowUpRight",
    metrics: {
      metricLabels: {
        forward_query_total: "转发查询",
        forward_success_total: "成功",
        forward_error_total: "失败",
        forward_timeout_total: "超时",
        forward_latency_count: "延迟样本",
        forward_latency_sum_ms: "延迟累计(ms)",
        forward_upstream_query_total: "上游查询",
        forward_upstream_success_total: "上游成功",
        forward_upstream_error_total: "上游失败",
        forward_upstream_timeout_total: "上游超时",
        forward_upstream_latency_count: "上游延迟样本",
        forward_upstream_latency_sum_ms: "上游延迟累计(ms)",
      },
      metricHelp: {
        forward_query_total: "转发执行器发起的查询总数。",
        forward_success_total: "成功获得上游响应的查询总数。",
        forward_error_total: "上游返回错误或无法获得响应的查询总数。",
        forward_timeout_total: "因超时未得到上游响应的查询总数。",
        forward_latency_count: "纳入延迟统计的已完成查询数。",
        forward_latency_sum_ms: "所有已完成转发查询的总延迟（毫秒）。",
        forward_upstream_query_total: "向该上游发起的请求总数。",
        forward_upstream_success_total: "该上游返回成功响应的次数。",
        forward_upstream_error_total: "该上游请求失败的次数。",
        forward_upstream_timeout_total: "该上游请求超时的次数。",
        forward_upstream_latency_count: "纳入该上游延迟统计的请求数。",
        forward_upstream_latency_sum_ms: "该上游所有请求的总延迟（毫秒）。",
      },
      cardPriority: [
        "forward_query_total",
        "forward_timeout_total",
        "forward_error_total",
      ],
      derivedCard: [
        {
          kind: "percent",
          numerator: "forward_success_total",
          denominator: "forward_query_total",
          label: "成功率",
        },
        { kind: "latency", prefix: "forward", label: "平均延迟" },
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "concurrent",
        description:
          "定义多上游模式下的并发查询扇出数，运行时上限为 32 且不超过上游数量。",
        label: "并发上游数",
        type: "number",
        default: 1,
        advanced: true,
      },
      {
        key: "response_selection",
        description: "定义多上游并发返回不一致时的结果选择策略。",
        label: "结果选择",
        type: "select",
        default: "balanced",
        advanced: true,
        options: [
          { label: "最快响应", value: "fastest" },
          { label: "平衡", value: "balanced" },
          { label: "优先正向答案", value: "prefer_positive" },
          { label: "负向共识", value: "consensus" },
        ],
      },
      {
        key: "upstreams",
        description: "定义一个或多个上游目标。",
        label: "上游列表",
        type: "array",
        required: true,
        example: "udp://1.1.1.1:53",
        item: {
          type: "object",
          summaryFields: ["tag", "addr"],
          fields: [
            {
              key: "tag",
              description: "为单个上游提供日志标识，便于排查多上游竞争结果。",
              label: "上游标识",
              type: "text",
              example: "cf_udp",
            },
            {
              key: "addr",
              description: "定义上游地址、协议类型以及目标主机。",
              label: "上游地址",
              type: "text",
              required: true,
              example: "udp://1.1.1.1:53",
            },
            {
              key: "outbound",
              description:
                "引用 network.outbound.profiles 中的出站配置；留空时使用 network.outbound.default，本地 dial_addr、bootstrap、socks5 优先生效。",
              label: "出站配置",
              type: "select",
              dynamicOptions: "outboundProfiles",
              example: "profile-1",
              advanced: true,
            },
            {
              key: "dial_addr",
              description:
                "指定实际连接 IP，同时保留 addr 中的主机名用于 SNI、Host 和证书校验；与 bootstrap 同时配置时本字段优先生效。",
              label: "拨号 IP",
              type: "text",
              example: "203.0.113.53",
              advanced: true,
            },
            {
              key: "port",
              description: "覆盖协议默认端口。",
              label: "端口覆盖",
              type: "number",
              example: "443",
              advanced: true,
            },
            {
              key: "bootstrap",
              description:
                "为域名型上游提供引导解析服务器；未配置时会在首次建连时使用系统解析；与 dial_addr 同时配置时会被忽略。",
              label: "Bootstrap",
              type: "text",
              example: "8.8.8.8:53",
              advanced: true,
            },
            {
              key: "bootstrap_version",
              description: "指定 bootstrap 优先使用 IPv4 或 IPv6。",
              label: "Bootstrap IP 版本",
              type: "select",
              advanced: true,
              options: [
                { label: "IPv4", value: 4 },
                { label: "IPv6", value: 6 },
              ],
            },
            {
              key: "socks5",
              description: "为上游连接指定 SOCKS5 代理。",
              label: "SOCKS5 代理",
              type: "text",
              example: "user:pass@127.0.0.1:1080",
              advanced: true,
            },
            {
              key: "idle_timeout",
              description: "定义连接池空闲连接保留时间。",
              label: "连接空闲超时(秒)",
              type: "number",
              example: "30",
              advanced: true,
            },
            {
              key: "max_conns",
              description: "定义连接池连接上限，范围 1..4096。",
              label: "最大连接数",
              type: "number",
              example: "256",
              advanced: true,
            },
            {
              key: "min_conns",
              description:
                "定义连接池最小预热连接数，默认 0，范围 0..4096，且不能大于 max_conns。",
              label: "最小连接数",
              type: "number",
              default: 0,
              advanced: true,
            },
            {
              key: "insecure_skip_verify",
              description: "控制是否跳过 TLS 证书校验。",
              label: "跳过 TLS 校验",
              type: "switch",
              default: false,
            },
            {
              key: "timeout",
              description: "定义单次上游查询超时。",
              label: "查询超时",
              type: "duration",
              default: "5s",
              example: "3s",
              advanced: true,
            },
            {
              key: "enable_pipeline",
              description: "控制 TCP 或 DoT 流水线。",
              label: "启用 Pipeline",
              type: "switch",
              advanced: true,
            },
            {
              key: "enable_http3",
              description: "控制 DoH 是否使用 HTTP/3。",
              label: "启用 HTTP/3",
              type: "switch",
              default: false,
              advanced: true,
            },
            {
              key: "so_mark",
              description: "设置 Linux SO_MARK。",
              label: "SO_MARK",
              type: "number",
              example: "100",
              advanced: true,
            },
            {
              key: "bind_to_device",
              description: "设置 Linux SO_BINDTODEVICE。",
              label: "绑定网卡",
              type: "text",
              example: "eth0",
              advanced: true,
            },
          ],
        },
      },
      {
        key: "short_circuit",
        description: "控制在拿到成功上游响应后，是否立即停止后续 executor 链。",
        label: "成功后停止后续执行",
        type: "switch",
        default: false,
      },
    ],
    quickSetup: {
      paramPlaceholder: "1.1.1.1 short_circuit=true",
    },
  },
  {
    kind: "cache",
    type: "executor",
    name: "Cache",
    description: "TTL 感知缓存，支持负缓存、lazy cache 与持久化",
    icon: "Database",
    metrics: {
      metricLabels: {
        cache_lookup_total: "缓存查询",
        cache_hit_total: "命中",
        cache_miss_total: "未命中",
        cache_expired_total: "过期",
        cache_insert_total: "写入",
        cache_skip_total: "跳过",
        cache_lazy_refresh_total: "懒刷新",
        cache_entry_count: "条目数",
      },
      metricHelp: {
        cache_lookup_total: "带有可缓存请求键的缓存查询总数。",
        cache_hit_total:
          "按新鲜度分类的缓存命中总数（fresh = 直接命中，stale = 过期可用）。",
        cache_miss_total: "缓存未命中的查询总数。",
        cache_expired_total: "查找时发现并移除过期条目的次数。",
        cache_insert_total: "缓存条目插入或更新的总次数。",
        cache_skip_total:
          "因写入策略（截断响应、无 TTL、正响应 TTL 过低）而跳过缓存的响应总数。",
        cache_lazy_refresh_total:
          "Lazy Cache 后台刷新尝试总数（按结果：started / success / failed）。",
        cache_entry_count: "当前缓存中的条目数量。",
      },
      cardPriority: [
        "cache_entry_count",
        "cache_lookup_total",
        "cache_miss_total",
        "cache_expired_total",
        "cache_skip_total",
      ],
      derivedCard: [
        {
          kind: "percent",
          numerator: "cache_hit_total",
          denominator: "cache_lookup_total",
          label: "命中率",
        },
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "size",
        description: "定义缓存最大条目数。",
        label: "最大条目数",
        type: "number",
        default: 1024,
      },
      {
        key: "lazy_cache_ttl",
        description: "为正向成功响应启用 lazy cache。",
        label: "Lazy Cache TTL(秒)",
        type: "number",
      },
      {
        key: "dump_file",
        description: "指定缓存持久化文件路径。",
        label: "持久化文件",
        type: "text",
        example: "./dns_cache.dump",
        advanced: true,
      },
      {
        key: "dump_interval",
        description: "定义缓存定期落盘周期。",
        label: "落盘周期(秒)",
        type: "number",
        default: 600,
        advanced: true,
      },
      {
        key: "short_circuit",
        description: "控制缓存命中后是否立即结束后续执行。",
        label: "命中后停止后续执行",
        type: "switch",
      },
      {
        key: "cache_negative",
        description: "控制是否缓存 NXDOMAIN 与 NODATA。",
        label: "缓存负响应",
        type: "switch",
      },
      {
        key: "max_negative_ttl",
        description: "定义负缓存 TTL 上限。",
        label: "负缓存 TTL 上限",
        type: "number",
        default: 300,
        advanced: true,
      },
      {
        key: "negative_ttl_without_soa",
        description: "定义无 SOA 负响应的回退 TTL。",
        label: "无 SOA 负缓存 TTL",
        type: "number",
        default: 60,
        advanced: true,
      },
      {
        key: "max_positive_ttl",
        description: "定义正响应 TTL 上限。",
        label: "正响应 TTL 上限",
        type: "number",
        advanced: true,
      },
      {
        key: "min_positive_ttl",
        description: "定义正响应进入缓存所需的最小 TTL。",
        label: "正响应最小缓存 TTL",
        type: "number",
        advanced: true,
      },
      {
        key: "ecs_in_key",
        description: "控制 ECS scope 是否参与缓存键计算。",
        label: "ECS 参与缓存键",
        type: "switch",
        default: false,
        advanced: true,
      },
    ],
    quickSetup: {
      paramPlaceholder: "short_circuit=true",
    },
  },
  {
    kind: "fallback",
    type: "executor",
    name: "Fallback",
    description: "主路径失败或过慢时切换到备用执行器",
    icon: "GitBranch",
    metrics: {
      metricLabels: {
        fallback_primary_total: "主链",
        fallback_primary_error_total: "主链失败",
        fallback_secondary_total: "降级",
      },
      metricHelp: {
        fallback_primary_total: "主执行器被调用的总次数。",
        fallback_primary_error_total: "主执行器未能产生响应的总次数。",
        fallback_secondary_total: "备用执行器被调用的总次数。",
      },
      cardPriority: [
        "fallback_secondary_total",
        "fallback_primary_error_total",
        "fallback_primary_total",
      ],
      derivedCard: [
        {
          kind: "percent",
          numerator: "fallback_secondary_total",
          denominator: "fallback_primary_total",
          label: "降级率",
        },
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      executorRef("primary", "主执行器", true, undefined, "指定主执行器。"),
      executorRef(
        "secondary",
        "备用执行器",
        true,
        undefined,
        "指定备用执行器。",
      ),
      {
        key: "threshold",
        description: "定义主路径超时或延迟判定阈值。",
        label: "接管阈值(ms)",
        type: "number",
        default: 0,
      },
      {
        key: "always_standby",
        description: "控制备用路径是否与主路径同时待命。",
        label: "备用路径并行待命",
        type: "switch",
        default: false,
        advanced: true,
      },
      {
        key: "short_circuit",
        description:
          "控制在主/备路径选出最终响应后，是否立即停止后续 executor 链。",
        label: "成功后停止后续执行",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "hosts",
    type: "executor",
    name: "Hosts",
    description: "按域名规则直接返回静态 A / AAAA",
    icon: "FileText",
    metrics: {
      metricLabels: {
        hosts_hit_total: "命中",
        hosts_miss_total: "未命中",
      },
      metricHelp: {
        hosts_hit_total: "命中 hosts 规则并生成本地响应的总次数。",
        hosts_miss_total: "未命中任何 hosts 规则的查询总次数。",
      },
      cardPriority: ["hosts_hit_total", "hosts_miss_total"],
      derivedCard: [
        {
          kind: "percent_of_sum",
          numerator: "hosts_hit_total",
          terms: ["hosts_hit_total", "hosts_miss_total"],
          label: "命中率",
        },
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      stringArrayField(
        "entries",
        "内联 hosts 规则",
        "router.local 192.168.1.1\nfull:gateway.local 192.168.1.2\ndomain:svc.local 10.0.0.10\nkeyword:nas 192.168.1.20\nregexp:^api[0-9]+\\.corp\\.local$ 10.10.0.5",
        false,
        "定义内联 hosts 规则。",
      ),
      stringArrayField(
        "files",
        "hosts 文件",
        "/etc/oxidns/hosts.txt",
        false,
        "指定外部 hosts 规则文件列表。",
      ),
      {
        key: "short_circuit",
        description: "命中并生成本地应答后，是否立即停止后续 executor 链。",
        label: "命中后停止后续执行",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "arbitrary",
    type: "executor",
    name: "Arbitrary",
    description: "加载静态 DNS 记录并在命中时构造应答",
    icon: "FileQuestion",
    configSchema: [
      stringArrayField(
        "rules",
        "静态记录",
        'example.com. 60 IN TXT "hello world"\nwww.example.com. 120 IN A 192.0.2.10',
        false,
        "定义内联静态记录列表。",
      ),
      stringArrayField(
        "files",
        "记录文件",
        "/etc/oxidns/zone.txt",
        false,
        "指定静态记录文件列表。",
      ),
      {
        key: "short_circuit",
        description: "命中并生成本地响应后，是否立即停止后续 executor 链。",
        label: "命中后停止后续执行",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "response",
    type: "executor",
    name: "Response",
    description:
      "构造并覆盖完整 DNS 响应，可分别配置 Answer、Authority 和 Additional",
    icon: "Reply",
    configSchema: [
      {
        key: "rcode",
        label: "响应码",
        type: "text",
        default: "NOERROR",
        example: "NOERROR / NXDOMAIN / 3",
        description: "基础 DNS RCODE，支持十进制数字或大小写不敏感的助记名。",
      },
      {
        key: "authoritative",
        label: "权威应答 (AA)",
        type: "switch",
        default: false,
        advanced: true,
        description: "设置 DNS 响应的 Authoritative Answer 标志。",
      },
      {
        key: "authentic_data",
        label: "已验证数据 (AD)",
        type: "switch",
        default: false,
        advanced: true,
        description: "设置 DNS 响应的 Authentic Data 标志。",
      },
      stringArrayField(
        "answers",
        "Answer 记录",
        "{qname} 300 {qclass} A 192.0.2.10",
        false,
        "每项一条 zone 风格 RR；{qname} 和 {qclass} 分别引用首个查询名称和类别。",
      ),
      stringArrayField(
        "authorities",
        "Authority 记录",
        "{qname} 300 {qclass} SOA ns.example. hostmaster.example. 1 7200 1800 86400 300",
        false,
        "每项一条 zone 风格 RR；NODATA 负缓存通常在此处配置 SOA。",
      ),
      stringArrayField(
        "additionals",
        "Additional 记录",
        "mail.example.com. 300 IN A 192.0.2.25",
        false,
        "每项一条 zone 风格 RR。",
      ),
      {
        key: "short_circuit",
        label: "生成后停止后续执行",
        type: "switch",
        default: true,
        description: "默认立即终止当前 executor 链；关闭后继续执行后续规则。",
      },
    ],
  },
  {
    kind: "redirect",
    type: "executor",
    name: "Redirect",
    description: "改写请求域名，配合 forward 生成目标响应",
    icon: "Pencil",
    configSchema: [
      stringArrayField(
        "rules",
        "重定向规则",
        "full:old.example.com new.example.net\ndomain:legacy.example.com modern.example.net\nkeyword:staging staging-gateway.example.net\nregexp:^api[0-9]+\\.legacy\\.example\\.com$ api-gateway.example.net",
        false,
        "定义内联重定向规则。",
      ),
      stringArrayField(
        "files",
        "规则文件",
        "/etc/oxidns/redirect.txt",
        false,
        "指定外部重定向规则文件列表。",
      ),
    ],
  },
  {
    kind: "client_ip_from_ecs",
    type: "executor",
    name: "Client IP From ECS",
    description: "使用 EDNS Client Subnet 地址覆盖当前请求的客户端 IP",
    icon: "Network",
    configSchema: [
      stringArrayField(
        "args",
        "可信来源 IP / CIDR",
        "127.0.0.1\n10.0.0.0/24\n::1",
        false,
        "仅当原始客户端 IP 命中该列表时，才采用请求中的 ECS 地址；留空时由服务端默认允许 127.0.0.1 和 ::1。",
        undefined,
        [inputArrayItem("127.0.0.1")],
      ),
    ],
    quickSetup: {
      paramPlaceholder: "127.0.0.1 或 10.0.0.0/24",
    },
  },
  {
    kind: "ecs_handler",
    type: "executor",
    name: "ECS Handler",
    description: "处理 EDNS Client Subnet 的保留、注入和回程清理",
    icon: "Globe",
    configSchema: [
      {
        key: "forward",
        description: "控制是否保留客户端请求中已有的 ECS。",
        label: "保留客户端 ECS",
        type: "switch",
        default: false,
      },
      {
        key: "send",
        description: "控制在请求缺少 ECS 时，是否根据来源地址自动补充 ECS。",
        label: "缺失时发送 ECS",
        type: "switch",
        default: false,
      },
      {
        key: "preset",
        description: "指定固定的 ECS 来源地址。",
        label: "预设 ECS 地址",
        type: "text",
        example: "203.0.113.10",
      },
      {
        key: "mask4",
        description: "指定 IPv4 ECS 前缀长度。",
        label: "IPv4 前缀长度",
        type: "number",
        default: 24,
        advanced: true,
      },
      {
        key: "mask6",
        description: "指定 IPv6 ECS 前缀长度。",
        label: "IPv6 前缀长度",
        type: "number",
        default: 48,
        advanced: true,
      },
    ],
    quickSetup: {
      paramPlaceholder: "203.0.113.10/24",
    },
  },
  {
    kind: "forward_edns0opt",
    type: "executor",
    name: "Forward EDNS0 Opt",
    description: "把指定 EDNS0 option 从请求转发到响应",
    icon: "ArrowUpRight",
    configSchema: [
      stringArrayField(
        "codes",
        "Option Code",
        "10\n12",
        false,
        "定义允许从请求复制到响应中的 EDNS0 option code 集合。",
      ),
    ],
    quickSetup: {
      paramPlaceholder: "10,12",
    },
  },
  {
    kind: "ttl",
    type: "executor",
    name: "TTL",
    description: "固定、抬高或限制响应 TTL",
    icon: "Clock",
    configSchema: [
      {
        key: "fix",
        description: "将所有响应 TTL 固定为同一个值。",
        label: "固定 TTL",
        type: "number",
      },
      {
        key: "min",
        description: "定义 TTL 下限。",
        label: "TTL 下限",
        type: "number",
      },
      {
        key: "max",
        description: "定义 TTL 上限。",
        label: "TTL 上限",
        type: "number",
      },
    ],
    quickSetup: {
      paramPlaceholder: "300 / 60-600",
    },
  },
  {
    kind: "ip_selector",
    type: "executor",
    name: "IP Selector",
    description: "对响应中的 A / AAAA 地址进行测速排序与筛选",
    icon: "Gauge",
    metrics: {
      metricLabels: {
        ip_selector_probe_total: "探测",
        ip_selector_probe_latency_count: "延迟样本",
        ip_selector_probe_latency_sum_ms: "延迟累计(ms)",
        ip_selector_selected_total: "优选结果",
        ip_selector_cache_entries: "缓存条目",
        ip_selector_dropped_probe_total: "跳过探测",
      },
      metricHelp: {
        ip_selector_probe_total: "按测速方式和结果统计的 IP 探测次数。",
        ip_selector_probe_latency_count: "成功测速的延迟样本数。",
        ip_selector_probe_latency_sum_ms: "成功测速延迟累计值（毫秒）。",
        ip_selector_selected_total:
          "按 probe/cache/fallback 来源统计的优选次数。",
        ip_selector_cache_entries: "当前 IP 探测评分缓存条目数量。",
        ip_selector_dropped_probe_total:
          "由于并发限制或已有 in-flight 探测而未新启动的探测次数。",
      },
      cardPriority: [
        "ip_selector_cache_entries",
        "ip_selector_probe_total",
        "ip_selector_selected_total",
        "ip_selector_dropped_probe_total",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "selection_mode",
        description: "定义响应 IP 优选策略。",
        label: "优选模式",
        type: "select",
        default: "first_success",
        options: [
          { label: "First success", value: "first_success" },
          { label: "Best within budget", value: "best_within_budget" },
          { label: "Background", value: "background" },
        ],
      },
      {
        ...stringArrayField(
          "probe_methods",
          "测速方式",
          "ping\nnone",
          false,
          "定义用于评分响应 IP 的探测方式，支持 tcp:<port>、ping、none。",
        ),
        default: ["tcp:443", "tcp:80"],
      },
      {
        key: "outbound",
        description:
          "引用 network.outbound.profiles 中的出站配置，为 TCP 探测复用 profile proxy。",
        label: "出站配置",
        type: "select",
        dynamicOptions: "outboundProfiles",
        example: "profile-1",
        advanced: true,
      },
      {
        key: "socks5",
        description:
          "为 TCP 探测指定局部 SOCKS5 代理，优先于 outbound profile proxy。",
        label: "SOCKS5 代理",
        type: "text",
        example: "127.0.0.1:1080",
        advanced: true,
      },
      {
        key: "probe_stagger",
        description: "多种测速方式之间的错峰启动间隔。",
        label: "测速错峰(ms)",
        type: "number",
        default: 200,
        advanced: true,
      },
      {
        key: "probe_timeout",
        description: "单次 IP 探测超时时间。",
        label: "单次超时(ms)",
        type: "number",
        default: 600,
        advanced: true,
      },
      {
        key: "max_wait",
        description: "本次响应优选最多等待多久。",
        label: "最大等待(ms)",
        type: "number",
        default: 1000,
        advanced: true,
      },
      {
        key: "top_n",
        description: "保留排序后的前 N 个地址；0 表示只重排不删除。",
        label: "保留地址数",
        type: "number",
        default: 1,
      },
      {
        key: "dnssec_policy",
        description: "DNSSEC 敏感响应的处理策略。",
        label: "DNSSEC 策略",
        type: "select",
        default: "reorder_only",
        advanced: true,
        options: [
          { label: "Reorder only", value: "reorder_only" },
          { label: "Skip", value: "skip" },
        ],
      },
      {
        key: "max_parallel_probes",
        description: "插件级并发探测数量上限。",
        label: "最大并发探测",
        type: "number",
        default: 256,
        advanced: true,
      },
      {
        key: "cache",
        description: "配置 IP 探测评分缓存。",
        label: "评分缓存",
        type: "object",
        advanced: true,
        summaryFields: ["enabled", "size"],
        fields: [
          {
            key: "enabled",
            description: "是否启用探测评分缓存。",
            label: "启用缓存",
            type: "switch",
            default: true,
          },
          {
            key: "size",
            description: "缓存容量目标。",
            label: "缓存容量",
            type: "number",
            default: 4096,
          },
          {
            key: "ttl",
            description: "成功评分保留时间。",
            label: "成功 TTL(秒)",
            type: "number",
            default: 3600,
          },
          {
            key: "failure_ttl",
            description: "失败评分保留时间。",
            label: "失败 TTL(秒)",
            type: "number",
            default: 60,
          },
        ],
      },
    ],
    quickSetup: {
      paramPlaceholder: "best_within_budget tcp:443,tcp:80,ping",
    },
  },
  {
    kind: "prefer_ipv4",
    type: "executor",
    name: "Prefer IPv4",
    description: "双栈优选器，偏好 A 记录并抑制可替代的 AAAA 请求",
    icon: "Shuffle",
    configSchema: [
      {
        key: "probe_executor",
        description: "指定仅用于 preferred QTYPE 内部探针的执行器。",
        label: "探针执行器",
        type: "reference",
        referenceTypes: ["executor"],
        referencePrefix: "",
        example: "probe_v4",
      },
      {
        key: "cache",
        description: "控制是否缓存 preferred 类型存在状态。",
        label: "缓存偏好状态",
        type: "switch",
        default: true,
      },
      {
        key: "cache_ttl",
        description: "定义 preferred 状态缓存时长。",
        label: "偏好状态缓存 TTL(秒)",
        type: "number",
        default: 3600,
        advanced: true,
      },
    ],
    quickSetup: {},
  },
  {
    kind: "prefer_ipv6",
    type: "executor",
    name: "Prefer IPv6",
    description: "双栈优选器，偏好 AAAA 记录并抑制可替代的 A 请求",
    icon: "Shuffle",
    configSchema: [
      {
        key: "probe_executor",
        description: "指定仅用于 preferred QTYPE 内部探针的执行器。",
        label: "探针执行器",
        type: "reference",
        referenceTypes: ["executor"],
        referencePrefix: "",
        example: "probe_v6",
      },
      {
        key: "cache",
        description: "控制是否缓存 preferred 类型存在状态。",
        label: "缓存偏好状态",
        type: "switch",
        default: true,
      },
      {
        key: "cache_ttl",
        description: "定义 preferred 状态缓存时长。",
        label: "偏好状态缓存 TTL(秒)",
        type: "number",
        default: 3600,
        advanced: true,
      },
    ],
    quickSetup: {},
  },
  {
    kind: "black_hole",
    type: "executor",
    name: "Black Hole",
    description: "按模式生成全 qtype 本地拦截响应",
    icon: "Ban",
    metrics: {
      metricLabels: { blackhole_block_total: "拦截" },
      metricHelp: {
        blackhole_block_total: "black_hole 生成拦截响应的总次数。",
      },
      cardPriority: ["blackhole_block_total"],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "mode",
        label: "拦截模式",
        description:
          "定义拦截响应类型；未配置 ips 时默认 nxdomain，配置 ips 时默认 custom。",
        type: "select",
        options: [
          { label: "NXDOMAIN", value: "nxdomain" },
          { label: "NODATA", value: "nodata" },
          { label: "Null 地址", value: "null" },
          { label: "自定义地址", value: "custom" },
          { label: "REFUSED", value: "refused" },
        ],
      },
      stringArrayField(
        "ips",
        "自定义返回地址",
        "0.0.0.0\n::",
        false,
        "定义 custom 模式使用的本地合成返回地址集合。",
      ),
      {
        key: "short_circuit",
        description: "生成拦截响应后，是否立即停止后续 executor 链。",
        label: "命中后停止后续执行",
        type: "switch",
        default: false,
      },
    ],
    quickSetup: {
      paramPlaceholder: "nxdomain short_circuit=true",
    },
  },
  {
    kind: "drop_resp",
    type: "executor",
    name: "Drop Response",
    description: "清空当前上下文中的响应",
    icon: "Ban",
    configSchema: [],
    quickSetup: {},
  },
  {
    kind: "reverse_lookup",
    type: "executor",
    name: "Reverse Lookup",
    description: "缓存 IP 到域名关系，并可选直接处理 PTR 查询",
    icon: "Database",
    metrics: {
      metricLabels: {
        reverse_lookup_ptr_hit_total: "PTR 命中",
        reverse_lookup_ptr_miss_total: "PTR 未命中",
        reverse_lookup_cache_insert_total: "缓存写入",
        reverse_lookup_cache_entries: "缓存条目",
      },
      metricHelp: {
        reverse_lookup_ptr_hit_total: "从反查缓存成功响应 PTR 查询的总次数。",
        reverse_lookup_ptr_miss_total: "PTR 查询未命中反查缓存的总次数。",
        reverse_lookup_cache_insert_total: "写入 IP → 域名映射条目的总次数。",
        reverse_lookup_cache_entries: "当前反查缓存中的条目数量。",
      },
      cardPriority: [
        "reverse_lookup_cache_entries",
        "reverse_lookup_ptr_hit_total",
        "reverse_lookup_ptr_miss_total",
        "reverse_lookup_cache_insert_total",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "size",
        description: "定义反查缓存容量上限。",
        label: "反查缓存容量",
        type: "number",
        default: 65535,
        advanced: true,
      },
      {
        key: "handle_ptr",
        description: "控制是否直接用反查缓存响应 PTR 请求。",
        label: "直接响应 PTR",
        type: "switch",
        default: false,
      },
      {
        key: "ttl",
        description: "定义 IP 到域名映射的缓存 TTL。",
        label: "映射 TTL(秒)",
        type: "number",
        default: 7200,
        advanced: true,
      },
    ],
  },
  {
    kind: "query_summary",
    type: "executor",
    name: "Query Summary",
    description: "在后续链路执行完后输出紧凑查询摘要",
    icon: "FileText",
    configSchema: [
      {
        key: "msg",
        description: "定义摘要日志标题。",
        label: "日志标题",
        type: "text",
        example: "main pipeline",
        default: "query summary",
      },
    ],
    quickSetup: {
      paramPlaceholder: "main pipeline",
    },
  },
  {
    kind: "learn_domain",
    type: "executor",
    name: "Learn Domain",
    description: "把请求域名写入 dynamic_domain_set，用于动态规则学习",
    icon: "Pencil",
    configSchema: [
      {
        key: "provider",
        description: "引用目标 dynamic_domain_set provider。",
        label: "目标 Provider",
        type: "reference",
        required: true,
        referenceTypes: ["provider"],
        referencePrefix: "",
        example: "learned_allow",
      },
      {
        key: "phase",
        description: "控制在下游 executor 之前学习，还是响应返回后学习。",
        label: "学习阶段",
        type: "select",
        options: [
          { label: "Before", value: "before" },
          { label: "After", value: "after" },
        ],
        default: "after",
      },
      {
        key: "questions",
        description: "控制学习第一个 question 或所有 question。",
        label: "Questions",
        type: "select",
        options: [
          { label: "First", value: "first" },
          { label: "All", value: "all" },
        ],
        default: "first",
      },
      {
        ...stringArrayField(
          "qtypes",
          "查询类型",
          "HTTPS\nSVCB",
          false,
          "只学习指定 DNS 查询类型。",
        ),
        default: ["A", "AAAA"],
      },
      {
        key: "success_only",
        description: "仅响应为 NOERROR 时学习；只在 after 阶段生效。",
        label: "仅成功响应",
        type: "switch",
        default: true,
      },
      {
        key: "answer_required",
        description: "仅响应包含 answer 时学习；只在 after 阶段生效。",
        label: "需要 Answer",
        type: "switch",
        default: true,
      },
      {
        key: "rule_kind",
        description: "控制写入 dynamic_domain_set 的规则类型。",
        label: "规则类型",
        type: "select",
        options: [
          { label: "Full", value: "full" },
          { label: "Domain", value: "domain" },
        ],
        default: "full",
      },
      {
        key: "async",
        description: "控制是否只入队后继续执行；关闭后会等待写入完成。",
        label: "异步写入",
        type: "switch",
        default: true,
        advanced: true,
      },
      {
        key: "error_mode",
        description: "控制学习失败后的执行行为。",
        label: "错误处理",
        type: "select",
        options: [
          { label: "Continue", value: "continue" },
          { label: "Stop", value: "stop" },
          { label: "Fail", value: "fail" },
        ],
        default: "continue",
      },
      {
        key: "timeout",
        description: "async 关闭时等待 provider 写入完成的最长时间。",
        label: "同步超时",
        type: "duration",
        default: "1s",
        advanced: true,
      },
    ],
  },
  {
    kind: "query_recorder",
    type: "executor",
    name: "Query Recorder",
    description: "将请求、响应和 sequence 路径事件持久化到 SQLite",
    icon: "Database",
    configSchema: [
      {
        key: "path",
        description: "指定当前 recorder 的 SQLite 文件路径。",
        label: "SQLite 文件",
        type: "text",
        required: true,
        example: "./data/query-recorder-main.sqlite",
      },
      {
        key: "queue_size",
        description: "定义热路径到后台写线程的有界队列大小。",
        label: "队列大小",
        type: "number",
        default: 8192,
        advanced: true,
      },
      {
        key: "batch_size",
        description: "定义后台批量写入 SQLite 的单批记录数。",
        label: "批量写入条数",
        type: "number",
        default: 256,
        advanced: true,
      },
      {
        key: "flush_interval_ms",
        description: "定义后台写线程的批量 flush 间隔。",
        label: "Flush 间隔(ms)",
        type: "number",
        default: 200,
        advanced: true,
      },
      {
        key: "memory_tail",
        description: "定义最近记录的内存 tail 长度，用于 stream?tail=n 回放。",
        label: "内存 Tail 长度",
        type: "number",
        default: 1024,
        advanced: true,
      },
      {
        key: "retention_days",
        description: "定义日志保留天数；过期数据会被定时实际删除。",
        label: "保留天数",
        type: "number",
        default: 7,
      },
      {
        key: "cleanup_interval_hours",
        description: "定义过期清理任务的执行周期。",
        label: "清理周期(小时)",
        type: "number",
        default: 1,
        advanced: true,
      },
      {
        key: "reader_concurrency",
        description:
          "限制 query_recorder API/统计读取侧同时运行的 SQLite reader 数量，避免 WebUI 或 API 突发请求占用过多阻塞线程和内存。",
        label: "读取并发数",
        type: "number",
        default: 2,
        advanced: true,
      },
    ],
  },
  {
    kind: "metrics_collector",
    type: "executor",
    name: "Metrics Collector",
    description: "收集轻量级请求计数与延时指标并导出 Prometheus 格式",
    icon: "Gauge",
    metrics: {
      metricLabels: {
        query_total: "总查询",
        query_error_total: "查询错误",
        query_inflight: "处理中",
        query_latency_count: "延迟样本",
        query_latency_sum_ms: "延迟累计(ms)",
      },
      metricHelp: {
        query_total: "metrics_collector 观测到的 DNS 查询总数。",
        query_error_total: "未产生响应的查询总数（错误或无响应）。",
        query_inflight: "当前正在处理中的 DNS 查询数量。",
        query_latency_count: "纳入延迟统计的已完成查询数。",
        query_latency_sum_ms: "所有已完成查询的总延迟（毫秒）。",
      },
      cardPriority: ["query_total", "query_error_total", "query_inflight"],
      derivedCard: [
        { kind: "latency", prefix: "query", label: "平均延迟" },
        {
          kind: "percent",
          numerator: "query_error_total",
          denominator: "query_total",
          label: "错误率",
        },
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "name",
        description: "定义当前指标收集器的名称标签。",
        label: "指标名称",
        type: "text",
        default: "default",
      },
    ],
    quickSetup: {
      paramPlaceholder: "main",
    },
  },
  {
    kind: "debug_print",
    type: "executor",
    name: "Debug Print",
    description: "打印请求与响应对象，便于排查问题",
    icon: "FileText",
    configSchema: [
      {
        key: "msg",
        description: "定义日志输出标题。",
        label: "日志标题",
        type: "text",
        default: "debug print",
      },
    ],
    quickSetup: {
      paramPlaceholder: "cron refresh",
    },
  },
  {
    kind: "sleep",
    type: "executor",
    name: "Sleep",
    description: "为策略链加入可控异步延迟",
    icon: "Clock",
    configSchema: [
      {
        key: "duration",
        description: "定义当前请求在该执行器上的额外异步等待时间。",
        label: "延迟(ms)",
        type: "number",
        default: 0,
      },
    ],
    quickSetup: {
      paramPlaceholder: "250ms / 2s",
    },
  },
  {
    kind: "http_request",
    type: "executor",
    name: "HTTP Request",
    description: "向外部 HTTP/HTTPS 服务发送 webhook、审计或联动请求",
    icon: "Globe",
    metrics: {
      metricLabels: {
        http_request_dispatch_total: "请求发起",
        http_request_error_total: "请求失败",
        http_request_dropped_total: "队列丢弃",
      },
      metricHelp: {
        http_request_dispatch_total:
          "http_request 执行器发起 HTTP 请求的总次数。",
        http_request_error_total:
          "HTTP 请求失败的总次数（渲染失败、发送失败或异步投递失败）。",
        http_request_dropped_total:
          "因异步队列已满或已关闭而丢弃的 HTTP 请求总数。",
      },
      cardPriority: [
        "http_request_dispatch_total",
        "http_request_error_total",
        "http_request_dropped_total",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "method",
        description: "指定 HTTP 方法，例如 GET、POST、PUT、PATCH、DELETE。",
        label: "HTTP 方法",
        type: "select",
        required: true,
        options: [
          { label: "GET", value: "GET" },
          { label: "POST", value: "POST" },
          { label: "PUT", value: "PUT" },
          { label: "PATCH", value: "PATCH" },
          { label: "DELETE", value: "DELETE" },
        ],
        initialValue: "POST",
      },
      {
        key: "url",
        description: "目标 URL。",
        label: "目标 URL",
        type: "text",
        required: true,
        example: "https://hooks.example.com/dns",
      },
      {
        key: "phase",
        description:
          "控制请求在下游 executor 之前发送，还是在下游执行完成后发送。",
        label: "触发阶段",
        type: "select",
        options: [
          { label: "Before", value: "before" },
          { label: "After", value: "after" },
        ],
        default: "after",
      },
      {
        key: "async",
        description:
          "控制使用异步后台队列发送，还是在当前请求路径同步等待 HTTP 完成。",
        label: "异步发送",
        type: "switch",
        default: true,
        advanced: true,
      },
      {
        key: "timeout",
        description: "限制单次 HTTP 调用的总超时时间。",
        label: "超时",
        type: "duration",
        default: "5s",
        advanced: true,
      },
      {
        key: "error_mode",
        description: "控制 HTTP 调用失败后的处理方式。",
        label: "错误处理",
        type: "select",
        options: [
          { label: "Continue", value: "continue" },
          { label: "Stop", value: "stop" },
          { label: "Fail", value: "fail" },
        ],
        default: "continue",
      },
      {
        key: "headers",
        description: "附加 HTTP 请求头。",
        label: "请求头",
        type: "record",
        keyPlaceholder: "X-Qname",
        valuePlaceholder: "${qname}",
      },
      {
        key: "query_params",
        description: "把额外参数追加到 URL query 上。",
        label: "Query 参数",
        type: "record",
        keyPlaceholder: "qname",
        valuePlaceholder: "${qname}",
      },
      {
        key: "body",
        description: "原始字符串请求体。",
        label: "原始 Body",
        type: "textarea",
        example: "qname=${qname}",
      },
      {
        key: "json",
        description: "以 JSON 方式发送请求体。",
        label: "JSON Body",
        type: "json",
        example: '{"qname":"${qname}","client_ip":"${client_ip}"}',
      },
      {
        key: "form",
        description: "以 application/x-www-form-urlencoded 方式发送表单。",
        label: "表单 Body",
        type: "record",
        keyPlaceholder: "qname",
        valuePlaceholder: "${qname}",
      },
      {
        key: "content_type",
        description: "为原始 args.body 指定 Content-Type。",
        label: "Content-Type",
        type: "text",
      },
      {
        key: "outbound",
        description:
          "引用 network.outbound.profiles 中的出站配置，用于统一控制解析器和代理。",
        label: "出站配置",
        type: "select",
        dynamicOptions: "outboundProfiles",
        example: "profile-1",
        advanced: true,
      },
      {
        key: "socks5",
        description: "指定 SOCKS5 代理。",
        label: "SOCKS5 代理",
        type: "text",
        example: "127.0.0.1:1080",
        advanced: true,
      },
      {
        key: "insecure_skip_verify",
        description: "是否跳过 HTTPS 证书校验。",
        label: "跳过 HTTPS 证书校验",
        type: "switch",
        default: false,
      },
      {
        key: "max_redirects",
        description: "限制最多跟随多少次重定向。",
        label: "最大重定向次数",
        type: "number",
        default: 5,
        advanced: true,
      },
      {
        key: "queue_size",
        description: "异步模式下后台发送队列的容量。",
        label: "异步队列大小",
        type: "number",
        default: 256,
        advanced: true,
      },
    ],
  },
  {
    kind: "script",
    type: "executor",
    name: "Script",
    description: "执行外部命令，并注入 DnsContext 中的稳定字段",
    icon: "Settings",
    metrics: {
      metricLabels: {
        script_run_total: "执行",
        script_success_total: "成功",
        script_error_total: "失败",
        script_timeout_total: "超时",
      },
      metricHelp: {
        script_run_total: "脚本执行器启动的外部命令总次数。",
        script_success_total: "外部命令正常退出（exit code 0）的总次数。",
        script_error_total:
          "外部命令执行失败（非零退出或运行时错误）的总次数。",
        script_timeout_total: "外部命令因超时被终止的总次数。",
      },
      cardPriority: [
        "script_run_total",
        "script_success_total",
        "script_error_total",
        "script_timeout_total",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "command",
        description: "要执行的命令路径或命令名。",
        label: "命令",
        type: "text",
        required: true,
        example: "bash",
      },
      stringArrayField(
        "args",
        "命令参数",
        "/etc/oxidns/notify.sh\n${qname}",
        false,
        "传给命令的参数数组。",
      ),
      {
        key: "env",
        description: "追加到子进程环境变量中的键值对。",
        label: "环境变量",
        type: "record",
        keyPlaceholder: "FDNS_QNAME",
        valuePlaceholder: "${qname}",
      },
      {
        key: "cwd",
        description: "指定脚本运行时的工作目录。",
        label: "工作目录",
        type: "text",
        example: "/etc/oxidns",
      },
      {
        key: "timeout",
        description: "限制单次脚本执行时长。",
        label: "超时",
        type: "duration",
        default: "5s",
        advanced: true,
      },
      {
        key: "error_mode",
        description: "控制脚本失败或超时后的处理方式。",
        label: "错误处理",
        type: "select",
        options: [
          { label: "Continue", value: "continue" },
          { label: "Stop", value: "stop" },
          { label: "Fail", value: "fail" },
        ],
        default: "continue",
      },
      {
        key: "max_output_bytes",
        description: "限制 stdout / stderr 的捕获长度，超过部分只做截断标记。",
        label: "最大输出捕获字节",
        type: "number",
        default: 4096,
        advanced: true,
      },
    ],
  },
  {
    kind: "ipset",
    type: "executor",
    name: "IPSet",
    description: "把响应中的 IP 写入 Linux ipset",
    icon: "MapPin",
    metrics: {
      metricLabels: {
        ipset_entries_total: "入队条目",
        ipset_dropped_total: "丢弃批次",
        ipset_write_total: "写入条目",
        ipset_write_error_total: "写入失败",
      },
      metricHelp: {
        ipset_entries_total: "排队等待写入 ipset 的 IP 条目总数。",
        ipset_dropped_total: "因写入队列已满而丢弃的批次总数。",
        ipset_write_total: "通过 netlink 成功写入 ipset 的 IP 条目总数。",
        ipset_write_error_total: "ipset netlink 写入失败的总次数。",
      },
      cardPriority: [
        "ipset_write_total",
        "ipset_write_error_total",
        "ipset_entries_total",
        "ipset_dropped_total",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "set_name4",
        description: "指定写入 IPv4 地址的 ipset 名称。",
        label: "IPv4 ipset 名称",
        type: "text",
      },
      {
        key: "set_name6",
        description: "指定写入 IPv6 地址的 ipset 名称。",
        label: "IPv6 ipset 名称",
        type: "text",
      },
      {
        key: "mask4",
        description: "指定 IPv4 地址写入 ipset 时使用的前缀长度。",
        label: "IPv4 前缀长度",
        type: "number",
        default: 24,
        advanced: true,
      },
      {
        key: "mask6",
        description: "指定 IPv6 地址写入 ipset 时使用的前缀长度。",
        label: "IPv6 前缀长度",
        type: "number",
        default: 32,
        advanced: true,
      },
    ],
    quickSetup: {
      paramPlaceholder: "oxidns_v4,inet,24 oxidns_v6,inet6,64",
    },
  },
  {
    kind: "nftset",
    type: "executor",
    name: "NFTSet",
    description: "把响应 IP 写入 Linux nftables set",
    icon: "MapPin",
    metrics: {
      metricLabels: {
        nftset_entries_total: "入队前缀",
        nftset_dropped_total: "丢弃批次",
        nftset_write_total: "写入前缀",
        nftset_write_error_total: "写入失败",
      },
      metricHelp: {
        nftset_entries_total: "排队等待写入 nftset 的 IP 前缀总数。",
        nftset_dropped_total: "因写入队列已满而丢弃的批次总数。",
        nftset_write_total: "通过 netlink 成功写入 nftables 的 IP 前缀总数。",
        nftset_write_error_total: "nftset netlink 写入失败的总次数。",
      },
      cardPriority: [
        "nftset_write_total",
        "nftset_write_error_total",
        "nftset_entries_total",
        "nftset_dropped_total",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "ipv4",
        description: "定义 IPv4 目标 nftables set。",
        label: "IPv4 目标",
        type: "object",
        fields: nftSetTargetFields,
        summaryFields: ["table_family", "table_name", "set_name"],
      },
      {
        key: "ipv6",
        description: "定义 IPv6 目标 nftables set。",
        label: "IPv6 目标",
        type: "object",
        fields: nftSetTargetFields.map((field) =>
          field.key === "table_family"
            ? { ...field, example: "ip6" }
            : field.key === "set_name"
              ? { ...field, example: "dns_v6" }
              : field,
        ),
        summaryFields: ["table_family", "table_name", "set_name"],
      },
      {
        key: "table_family4",
        description: "兼容写法下定义 IPv4 的 nftables 表 family。",
        label: "IPv4 表 family",
        type: "text",
        advanced: true,
      },
      {
        key: "table_name4",
        description: "兼容写法下定义 IPv4 的 nftables 表名。",
        label: "IPv4 表名",
        type: "text",
        advanced: true,
      },
      {
        key: "set_name4",
        description: "兼容写法下定义 IPv4 的 set 名称。",
        label: "IPv4 set 名称",
        type: "text",
        advanced: true,
      },
      {
        key: "mask4",
        description: "兼容写法下定义 IPv4 前缀长度。",
        label: "IPv4 前缀长度",
        type: "number",
        advanced: true,
      },
      {
        key: "table_family6",
        description: "兼容写法下定义 IPv6 的 nftables 表 family。",
        label: "IPv6 表 family",
        type: "text",
        advanced: true,
      },
      {
        key: "table_name6",
        description: "兼容写法下定义 IPv6 的 nftables 表名。",
        label: "IPv6 表名",
        type: "text",
        advanced: true,
      },
      {
        key: "set_name6",
        description: "兼容写法下定义 IPv6 的 set 名称。",
        label: "IPv6 set 名称",
        type: "text",
        advanced: true,
      },
      {
        key: "mask6",
        description: "兼容写法下定义 IPv6 前缀长度。",
        label: "IPv6 前缀长度",
        type: "number",
        advanced: true,
      },
    ],
    quickSetup: {
      paramPlaceholder: "ip,mangle,dns_v4,ipv4_addr,24",
    },
  },
  {
    kind: "ros_route",
    type: "executor",
    name: "RouterOS Route",
    description: "把应答 IP 同步为 RouterOS routing table 中的逐 IP 静态路由",
    icon: "Route",
    metrics: {
      metricLabels: {
        ros_route_observe_total: "地址观测",
        ros_route_dropped_total: "异步丢弃",
        ros_route_sync_error_total: "同步失败",
        ros_route_sync_timeout_total: "同步超时",
        ros_route_write_success_total: "写入成功",
        ros_route_write_error_total: "写入失败",
        ros_route_last_write_success_timestamp_seconds: "最近写入成功",
        ros_route_delete_deferred_total: "延迟删除",
        ros_route_connection_check_error_total: "连接检查失败",
        ros_route_pending_observations: "待处理观测",
        ros_route_managed_entries: "受管路由",
        ros_route_coalesced_total: "合并观测",
        ros_route_reconnect_total: "重连",
        ros_route_connect_attempt_total: "连接尝试",
        ros_route_backoff_total: "退避",
        ros_route_reconcile_error_total: "对账失败",
        ros_route_last_reconcile_success_timestamp_seconds: "最近对账成功",
        ros_route_degraded: "连接降级",
        ros_route_cleanup_error_total: "清理失败",
      },
      metricHelp: {
        ros_route_observe_total: "提交给 RouterOS 路由管理器的地址观测总数。",
        ros_route_dropped_total:
          "异步模式下因队列已满或通道关闭而丢弃的观测总数。",
        ros_route_sync_error_total:
          "同步模式下在 RouterOS 路由管理器侧失败的观测总数。",
        ros_route_sync_timeout_total:
          "同步模式下等待 manager 完成时超时的观测总数。",
        ros_route_write_success_total: "RouterOS 路由 upsert 成功总数。",
        ros_route_write_error_total: "RouterOS 路由 upsert 失败总数。",
        ros_route_last_write_success_timestamp_seconds:
          "最近一次 RouterOS 路由 upsert 成功的 Unix 时间。",
        ros_route_delete_deferred_total:
          "因 RouterOS conntrack 中仍存在目标连接而延迟删除路由的总次数。",
        ros_route_connection_check_error_total:
          "路由删除期间 RouterOS conntrack 查询失败的总次数。",
        ros_route_pending_observations: "当前等待 manager 处理的合并后观测数。",
        ros_route_managed_entries: "manager 当前保留的路由条目数。",
        ros_route_coalesced_total:
          "合并到已有 mailbox 路由 key 的地址观测总数。",
        ros_route_reconnect_total: "RouterOS transport 成功重连的总次数。",
        ros_route_connect_attempt_total:
          "RouterOS transport 发起连接尝试的总次数。",
        ros_route_backoff_total: "RouterOS transport 安排退避等待的总次数。",
        ros_route_reconcile_error_total: "常驻路由对账失败的总次数。",
        ros_route_last_reconcile_success_timestamp_seconds:
          "最近一次常驻路由对账成功的 Unix 时间。",
        ros_route_degraded: "RouterOS transport 当前是否处于降级状态。",
        ros_route_cleanup_error_total: "关闭清理失败的路由条目总数。",
      },
      cardPriority: [
        "ros_route_write_success_total",
        "ros_route_write_error_total",
        "ros_route_dropped_total",
        "ros_route_last_write_success_timestamp_seconds",
        "ros_route_managed_entries",
        "ros_route_pending_observations",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "address",
        label: "RouterOS API 地址",
        type: "text",
        required: true,
        example: "172.16.1.1:8728",
      },
      { key: "username", label: "用户名", type: "text", required: true },
      { key: "password", label: "密码", type: "password", required: true },
      {
        key: "tls",
        label: "TLS",
        type: "object",
        advanced: true,
        preserveEmptyObject: true,
        description: "启用 RouterOS API-SSL（通常为 8729 端口）。",
        fields: [
          { key: "server_name", label: "服务器名称", type: "text" },
          { key: "ca", label: "自定义 CA 文件", type: "text" },
          {
            key: "insecure",
            label: "跳过证书验证",
            type: "switch",
            default: false,
          },
        ],
      },
      {
        key: "connect_timeout",
        label: "连接超时",
        type: "number",
        default: 5,
        advanced: true,
      },
      {
        key: "send_timeout",
        label: "发送超时",
        type: "number",
        default: 5,
        advanced: true,
      },
      {
        key: "receive_timeout",
        label: "接收超时",
        type: "number",
        default: 5,
        advanced: true,
      },
      {
        key: "async",
        label: "异步提交",
        type: "switch",
        default: true,
        advanced: true,
      },
      {
        key: "wait_timeout",
        label: "同步等待时间",
        type: "text",
        default: "8s",
        advanced: true,
        description: "仅 async=false 时生效；超时后任务继续在后台执行。",
      },
      {
        key: "queue_capacity",
        label: "队列容量",
        type: "number",
        default: 16384,
        advanced: true,
      },
      {
        key: "routing_table",
        label: "路由表",
        type: "text",
        required: true,
        example: "via_proxy",
      },
      {
        key: "gateway4",
        label: "IPv4 网关",
        type: "text",
        example: "192.168.88.2@main",
      },
      {
        key: "gateway6",
        label: "IPv6 网关",
        type: "text",
        example: "fe80::2%ether1",
      },
      {
        key: "distance",
        label: "路由距离",
        type: "number",
        default: 100,
        advanced: true,
      },
      {
        key: "comment_prefix",
        label: "注释前缀",
        type: "text",
        default: "oxi",
        advanced: true,
      },
      {
        key: "persistent",
        label: "常驻路由",
        type: "object",
        description:
          "期望状态；启动恢复并每 180 秒对账。动态路由不参与定时对账。",
        advanced: true,
        fields: [
          stringArrayField("ips", "IP / CIDR", "1.1.1.1\n100.64.1.0/24", false),
          stringArrayField(
            "files",
            "文件",
            "/etc/oxidns/persistent_routes.txt",
            false,
          ),
        ],
      },
      {
        key: "min_ttl",
        label: "动态路由最小 TTL",
        type: "number",
        default: 60,
        advanced: true,
      },
      {
        key: "max_ttl",
        label: "动态路由最大 TTL",
        type: "number",
        default: 3600,
        advanced: true,
      },
      {
        key: "fixed_ttl",
        label: "动态路由固定 TTL",
        type: "number",
        description: "填 0 表示不按时间过期；动态路由只由后续 DNS 观察刷新。",
        advanced: true,
      },
      {
        key: "conntrack_guard",
        label: "连接跟踪保护",
        type: "switch",
        default: false,
        description:
          "删除到期动态主机路由前检查 RouterOS conntrack；有目标连接时延后删除。",
        advanced: true,
      },
      {
        key: "cleanup_on_shutdown",
        label: "关闭时清理",
        type: "switch",
        default: true,
        description:
          "正常关闭及应用级 reload 时清理；需要策略连续性时设为 false。",
        advanced: true,
      },
    ],
  },
  {
    kind: "ros_address_list",
    type: "executor",
    name: "RouterOS Address List",
    description:
      "把应答 IP 同步到供 firewall、mangle 或路由规则使用的 address-list",
    icon: "Network",
    metrics: {
      metricLabels: {
        ros_address_list_observe_total: "地址观测",
        ros_address_list_dropped_total: "异步丢弃",
        ros_address_list_sync_error_total: "同步失败",
        ros_address_list_sync_timeout_total: "同步超时",
        ros_address_list_write_success_total: "写入成功",
        ros_address_list_write_error_total: "写入失败",
        ros_address_list_last_write_success_timestamp_seconds: "最近写入成功",
        ros_address_list_pending_observations: "待处理观测",
        ros_address_list_managed_entries: "受管条目",
        ros_address_list_coalesced_total: "合并观测",
        ros_address_list_reconnect_total: "重连",
        ros_address_list_connect_attempt_total: "连接尝试",
        ros_address_list_backoff_total: "退避",
        ros_address_list_reconcile_error_total: "对账失败",
        ros_address_list_last_reconcile_success_timestamp_seconds:
          "最近对账成功",
        ros_address_list_degraded: "连接降级",
        ros_address_list_cleanup_error_total: "清理失败",
      },
      metricHelp: {
        ros_address_list_observe_total:
          "提交给 RouterOS address-list 管理器的地址观测总数。",
        ros_address_list_dropped_total:
          "异步模式下因队列已满或通道关闭而丢弃的观测总数。",
        ros_address_list_sync_error_total:
          "同步模式下在 RouterOS 管理器侧失败的观测总数。",
        ros_address_list_sync_timeout_total:
          "同步模式下等待 manager 完成时超时的观测总数。",
        ros_address_list_write_success_total:
          "RouterOS address-list upsert 成功总数。",
        ros_address_list_write_error_total:
          "RouterOS address-list upsert 失败总数。",
        ros_address_list_last_write_success_timestamp_seconds:
          "最近一次 RouterOS address-list upsert 成功的 Unix 时间。",
        ros_address_list_pending_observations:
          "当前等待 manager 处理的合并后观测数。",
        ros_address_list_managed_entries:
          "manager 当前保留的 address-list 条目数。",
        ros_address_list_degraded: "RouterOS transport 当前是否处于降级状态。",
      },
      cardPriority: [
        "ros_address_list_write_success_total",
        "ros_address_list_write_error_total",
        "ros_address_list_dropped_total",
        "ros_address_list_last_write_success_timestamp_seconds",
        "ros_address_list_managed_entries",
        "ros_address_list_pending_observations",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "address",
        description: "指定 RouterOS API 服务地址，通常写为 host:port。",
        label: "RouterOS API 地址",
        type: "text",
        required: true,
        example: "172.16.1.1:8728",
      },
      {
        key: "username",
        description: "指定 RouterOS API 登录用户名。",
        label: "用户名",
        type: "text",
        required: true,
      },
      {
        key: "tls",
        label: "TLS",
        type: "object",
        advanced: true,
        preserveEmptyObject: true,
        description: "启用 RouterOS API-SSL（通常为 8729 端口）。",
        fields: [
          { key: "server_name", label: "服务器名称", type: "text" },
          { key: "ca", label: "自定义 CA 文件", type: "text" },
          {
            key: "insecure",
            label: "跳过证书验证",
            type: "switch",
            default: false,
          },
        ],
      },
      {
        key: "password",
        description: "指定 RouterOS API 登录密码。",
        label: "密码",
        type: "password",
        required: true,
      },
      {
        key: "connect_timeout",
        description: "建立 RouterOS API 连接时的等待上限，单位秒。",
        label: "连接超时",
        type: "number",
        default: 5,
        advanced: true,
      },
      {
        key: "send_timeout",
        description: "发送单个 RouterOS API 命令时的等待上限，单位秒。",
        label: "发送超时",
        type: "number",
        default: 5,
        advanced: true,
      },
      {
        key: "receive_timeout",
        description: "等待下一段 RouterOS API 响应数据的上限，单位秒。",
        label: "接收超时",
        type: "number",
        default: 5,
        advanced: true,
      },
      {
        key: "async",
        description: "控制地址写入行为是否采用异步方式。",
        label: "异步提交",
        type: "switch",
        default: true,
        advanced: true,
      },
      {
        key: "wait_timeout",
        description: "仅 async=false 时生效；超时后任务继续在后台执行。",
        label: "同步等待时间",
        type: "text",
        default: "8s",
        advanced: true,
      },
      {
        key: "queue_capacity",
        label: "队列容量",
        type: "number",
        default: 16384,
        advanced: true,
      },
      {
        key: "address_list4",
        description: "指定 IPv4 地址写入的目标 address-list 名称。",
        label: "IPv4 Address List",
        type: "text",
      },
      {
        key: "address_list6",
        description: "指定 IPv6 地址写入的目标 address-list 名称。",
        label: "IPv6 Address List",
        type: "text",
      },
      {
        key: "comment_prefix",
        description: "指定插件写入 RouterOS 条目时使用的注释前缀。",
        label: "注释前缀",
        type: "text",
        default: "oxi",
        advanced: true,
      },
      {
        key: "persistent",
        description:
          "期望状态；启动恢复并每 180 秒对账。动态项不参与定时对账。",
        label: "常驻地址",
        type: "object",
        advanced: true,
        fields: [
          stringArrayField(
            "ips",
            "IP / CIDR",
            "1.1.1.1\n100.64.1.0/24",
            false,
            "以内联方式声明常驻 IP 或 CIDR 网段。",
            {
              type: "text",
              label: "输入值",
              example: "1.1.1.1",
            },
          ),
          stringArrayField(
            "files",
            "文件",
            "/etc/oxidns/persistent_ips.txt",
            false,
            "从外部文件加载常驻地址集合。",
            {
              type: "text",
              label: "输入值",
              example: "/etc/oxidns/persistent_ips.txt",
            },
          ),
        ],
      },
      {
        key: "min_ttl",
        description: "定义动态地址项允许使用的最小 TTL。",
        label: "动态项最小 TTL",
        type: "number",
        default: 60,
        advanced: true,
      },
      {
        key: "max_ttl",
        description: "定义动态地址项允许使用的最大 TTL。",
        label: "动态项最大 TTL",
        type: "number",
        default: 3600,
        advanced: true,
      },
      {
        key: "fixed_ttl",
        description: "为动态项指定固定 TTL；刷新只由后续 DNS 观察触发。",
        label: "动态项固定 TTL",
        type: "number",
        advanced: true,
      },
      {
        key: "cleanup_on_shutdown",
        description: "控制正常关闭及应用级 reload 时是否清理由其管理的条目。",
        label: "关闭时清理",
        type: "switch",
        default: true,
        advanced: true,
      },
    ],
  },
  {
    kind: "upgrade",
    type: "executor",
    name: "Upgrade",
    description: "执行 OxiDNS 升级流程",
    icon: "ArrowUpRight",
    configSchema: [
      {
        key: "force",
        description:
          "即使目标 release 不比当前版本更新，也继续下载、校验并替换。",
        label: "强制升级",
        type: "switch",
        default: false,
      },
      {
        key: "cleanup",
        description: "升级成功后清理 cache_dir 和 backup_dir。",
        label: "升级后清理缓存",
        type: "switch",
        default: true,
      },
      {
        key: "repository",
        description: "GitHub 仓库。",
        label: "GitHub 仓库",
        type: "text",
        default: "svenshi/oxidns",
      },
      {
        key: "asset",
        description:
          "Release asset 名称；auto 会根据当前平台和编译版本选择 archive。",
        label: "Release Asset",
        type: "text",
        default: "auto",
      },
      {
        key: "bundle",
        description:
          "asset 为 auto 时使用的编译版本；auto 会跟随当前二进制的编译版本。",
        label: "编译版本",
        type: "select",
        default: "auto",
        options: [
          { label: "Auto", value: "auto" },
          { label: "Full", value: "full" },
          { label: "Standard", value: "standard" },
          { label: "Minimal", value: "minimal" },
        ],
      },
      {
        key: "github_token",
        description:
          "GitHub 个人访问令牌，用于提高 API 速率限制或访问私有仓库。",
        label: "GitHub Token",
        type: "text",
        advanced: true,
      },
      {
        key: "cache_dir",
        description: "下载缓存目录。",
        label: "下载缓存目录",
        type: "text",
        example: "./upgrade/cache",
        advanced: true,
      },
      {
        key: "backup_dir",
        description: "替换前备份目录。",
        label: "备份目录",
        type: "text",
        example: "./upgrade/backups",
        advanced: true,
      },
      {
        key: "webui_dir",
        description: "升级时安装 WebUI 静态资源的目录。",
        label: "WebUI 目录",
        type: "text",
        default: "./webui",
        example: "/opt/oxidns/webui",
      },
      {
        key: "skip_webui",
        description: "apply 时跳过 WebUI 目录升级，仅替换二进制文件。",
        label: "跳过 WebUI 升级",
        type: "switch",
        default: false,
      },
      {
        key: "no_restart",
        description: "启用后升级成功也不会触发自动重启。",
        label: "跳过自动重启",
        type: "switch",
        default: false,
      },
      {
        key: "timeout",
        description: "限制升级过程的总等待时间。",
        label: "超时",
        type: "duration",
        default: "30s",
        advanced: true,
      },
      {
        key: "outbound",
        description:
          "引用 network.outbound.profiles 中的出站配置，用于升级下载。",
        label: "出站配置",
        type: "select",
        dynamicOptions: "outboundProfiles",
        example: "profile-1",
        advanced: true,
      },
      {
        key: "socks5",
        description: "升级下载时使用的 SOCKS5 代理。",
        label: "SOCKS5 代理",
        type: "text",
        example: "127.0.0.1:1080",
        advanced: true,
      },
      {
        key: "insecure_skip_verify",
        description: "升级下载时跳过 HTTPS 证书校验。",
        label: "跳过 HTTPS 证书校验",
        type: "switch",
        default: false,
      },
    ],
    quickSetup: {
      paramPlaceholder: "force=true",
    },
  },
  {
    kind: "download",
    type: "executor",
    name: "Download",
    description: "下载 HTTP/HTTPS 文件到本地目录并原子覆盖",
    icon: "File",
    metrics: {
      metricLabels: {
        download_success_total: "下载成功",
        download_failure_total: "下载失败",
        download_timeout_total: "下载超时",
      },
      metricHelp: {
        download_success_total: "成功完成的文件下载总次数。",
        download_failure_total: "下载失败的总次数（不含超时）。",
        download_timeout_total: "因超时中断的文件下载总次数。",
      },
      cardPriority: [
        "download_success_total",
        "download_failure_total",
        "download_timeout_total",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "downloads",
        description:
          "下载一个或多个 http/https 文件到本地目录，并在新内容完整写入后覆盖目标文件。",
        label: "下载项",
        type: "array",
        required: true,
        example:
          '[{"url":"https://example.com/geosite.dat","dir":"/etc/oxidns","filename":"geosite.dat"}]',
        item: {
          type: "object",
          label: "下载项",
          summaryFields: ["filename", "url"],
          fields: [
            {
              key: "url",
              description: "下载项的 http/https URL。",
              label: "URL",
              type: "text",
              required: true,
              example: "https://example.com/geosite.dat",
            },
            {
              key: "dir",
              description: "下载项的目标目录。",
              label: "目录",
              type: "text",
              required: true,
              example: "/etc/oxidns",
            },
            {
              key: "filename",
              description: "下载项的目标文件名。",
              label: "文件名",
              type: "text",
              example: "geosite.dat",
            },
          ],
        },
      },
      {
        key: "timeout",
        description: "下载超时时间。",
        label: "超时",
        type: "duration",
        default: "30s",
        advanced: true,
      },
      {
        key: "outbound",
        description:
          "引用 network.outbound.profiles 中的出站配置，用于统一控制下载解析器和代理。",
        label: "出站配置",
        type: "select",
        dynamicOptions: "outboundProfiles",
        example: "profile-1",
        advanced: true,
      },
      {
        key: "socks5",
        description: "所有下载连接都会通过该 SOCKS5 代理发起。",
        label: "SOCKS5 代理",
        type: "text",
        example: "127.0.0.1:1080",
        advanced: true,
      },
      {
        key: "startup_if_missing",
        description: "启动时检查目标文件，缺失项会在其它插件初始化前自动下载。",
        label: "启动时补齐缺失文件",
        type: "switch",
        default: true,
      },
    ],
    quickSetup: {
      paramPlaceholder: "https://example.com/rules.txt /etc/oxidns",
    },
  },
  {
    kind: "reload_provider",
    type: "executor",
    name: "Reload Provider",
    description: "按 tag 定向刷新一个或多个 provider",
    icon: "RefreshCw",
    metrics: {
      metricLabels: {
        reload_provider_reload_total: "数据源重载",
        reload_provider_reload_error_total: "重载失败",
      },
      metricHelp: {
        reload_provider_reload_total:
          "该执行器触发的 provider 重载尝试总次数。",
        reload_provider_reload_error_total: "provider 重载失败的总次数。",
      },
      cardPriority: [
        "reload_provider_reload_total",
        "reload_provider_reload_error_total",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      stringArrayField(
        "args",
        "Provider 引用",
        "$geosite_cn\n$geoip_cn",
        true,
        "按 args 中声明顺序逐个执行 targeted provider reload。",
        {
          type: "reference",
          referenceTypes: ["provider"],
          referencePrefix: "$",
          example: "geosite_cn",
        },
      ),
    ],
    quickSetup: {
      paramPlaceholder: "$geosite_cn",
      paramReferenceTypes: ["provider"],
    },
  },
  {
    kind: "reload",
    type: "executor",
    name: "Reload",
    description: "触发一次应用级全量 reload",
    icon: "RefreshCw",
    metrics: {
      metricLabels: {
        reload_trigger_total: "重载触发",
        reload_error_total: "重载失败",
      },
      metricHelp: {
        reload_trigger_total: "该执行器请求应用级全量 reload 的总次数。",
        reload_error_total: "重载请求调度失败的总次数。",
      },
      cardPriority: ["reload_trigger_total", "reload_error_total"],
    } satisfies PluginMetricsDef,
    configSchema: [],
    quickSetup: {},
  },
  {
    kind: "cron",
    type: "executor",
    name: "Cron",
    description: "后台按 cron 或固定间隔调度一组 executor",
    icon: "Clock",
    metrics: {
      metricLabels: {
        cron_job_run_total: "任务运行",
        cron_job_skipped_total: "重叠跳过",
        cron_executor_error_total: "执行器失败",
      },
      metricHelp: {
        cron_job_run_total: "Cron 任务被启动的总次数。",
        cron_job_skipped_total: "因上次运行尚未结束而跳过本次触发的总次数。",
        cron_executor_error_total: "Cron 任务运行中各执行器失败的总次数。",
      },
      cardPriority: [
        "cron_job_run_total",
        "cron_job_skipped_total",
        "cron_executor_error_total",
      ],
    } satisfies PluginMetricsDef,
    configSchema: [
      {
        key: "jobs",
        description: "定义一个或多个后台任务。",
        label: "任务列表",
        type: "array",
        required: true,
        example:
          '[{"name":"refresh_sets","interval":"5m","executors":["$seq_refresh"]}]',
        item: {
          type: "object",
          label: "任务",
          summaryFields: ["name", "interval", "schedule"],
          fields: [
            {
              key: "name",
              description: "任务名称，用于日志与运行时标识。",
              label: "任务名称",
              type: "text",
              required: true,
              example: "refresh_sets",
            },
            {
              key: "schedule",
              description: "使用标准 5 字段 cron 表达式调度任务。",
              label: "Cron 表达式",
              type: "text",
              example: "0 */6 * * *",
            },
            {
              key: "interval",
              description: "用简单固定间隔调度任务。",
              label: "固定间隔",
              type: "duration",
              example: "5m",
            },
            {
              key: "executors",
              description: "定义任务触发时顺序执行的 executor 列表。",
              label: "执行器",
              type: "array",
              required: true,
              example: "$seq_refresh\ndebug_print cron refresh",
              itemOptions: [
                executorReferenceArrayItem("seq_refresh"),
                inputArrayItem("debug_print cron refresh"),
              ],
            },
          ],
        },
      },
      {
        key: "timezone",
        description: "为当前 cron 插件下的所有 schedule 任务指定时区。",
        label: "时区",
        type: "text",
        example: "Asia/Shanghai",
        advanced: true,
      },
    ],
  },
];
