import type { PluginKindDefinition, PluginMetricsDef } from "./shared";
import { executorRef } from "./shared";

const serverMetrics: PluginMetricsDef = {
  metricLabels: {
    server_request_total: "请求总数",
    server_completed_total: "完成",
    server_controlled_total: "提前结束",
    server_failed_total: "失败(SERVFAIL)",
    server_inflight: "处理中",
    server_latency_count: "延迟样本",
    server_latency_sum_ms: "延迟累计(ms)",
  },
  metricHelp: {
    server_request_total: "服务器接收并处理的入站 DNS 请求总数。",
    server_completed_total: "执行器链正常执行完毕的请求总数。",
    server_controlled_total:
      "执行器主动停止（stop/return）而提前结束的请求总数。",
    server_failed_total: "因入口执行器失败而返回 SERVFAIL 的请求总数。",
    server_inflight: "当前服务器正在处理中的请求数量。",
    server_latency_count: "纳入服务器延迟统计的已完成请求数。",
    server_latency_sum_ms: "所有已完成请求的总处理延迟（毫秒）。",
  },
  cardPriority: [
    "server_request_total",
    "server_inflight",
    "server_failed_total",
    "server_controlled_total",
  ],
  derivedCard: [
    { kind: "latency", prefix: "server", label: "平均延迟" },
    {
      kind: "percent",
      numerator: "server_failed_total",
      denominator: "server_request_total",
      label: "失败率",
    },
  ],
};

export const serverPluginDefinitions: PluginKindDefinition[] = [
  {
    kind: "udp_server",
    type: "server",
    name: "UDP Server",
    description: "标准 DNS UDP 入口，把请求交给指定执行器",
    icon: "Wifi",
    metrics: serverMetrics,
    configSchema: [
      executorRef(
        "entry",
        "入口执行器",
        true,
        undefined,
        "指定处理该监听器全部请求的入口执行器，通常为sequence插件。",
      ),
      {
        key: "listen",
        description: "指定 UDP 监听地址。",
        label: "监听地址",
        type: "text",
        example: "0.0.0.0:53",
        required: true,
      },
    ],
  },
  {
    kind: "tcp_server",
    type: "server",
    name: "TCP / DoT Server",
    description: "DNS over TCP；配置证书后作为 DoT 入口",
    icon: "Network",
    metrics: serverMetrics,
    configSchema: [
      executorRef(
        "entry",
        "入口执行器",
        true,
        undefined,
        "指定 TCP 或 DoT 请求进入策略链时使用的入口执行器。",
      ),
      {
        key: "listen",
        description: "指定 TCP 监听地址。",
        label: "监听地址",
        type: "text",
        example: ":53",
        required: true,
      },
      {
        key: "cert",
        description: "指定 TLS 证书文件路径。",
        label: "TLS 证书",
        type: "text",
        example: "/etc/oxidns/server.crt",
      },
      {
        key: "key",
        description: "指定 TLS 私钥文件路径。",
        label: "TLS 私钥",
        type: "text",
        example: "/etc/oxidns/server.key",
      },
      {
        key: "idle_timeout",
        description: "指定连接空闲超时设置。",
        label: "空闲超时(秒)",
        type: "number",
        default: 10,
        advanced: true,
      },
    ],
  },
  {
    kind: "http_server",
    type: "server",
    name: "HTTP / DoH Server",
    description: "DNS over HTTPS，支持路径到执行器的多入口映射",
    icon: "Lock",
    metrics: serverMetrics,
    configSchema: [
      {
        key: "entries",
        description: "定义 HTTP 路径到执行器的映射关系。",
        label: "路径映射",
        type: "array",
        required: true,
        example: '[{"path":"/dns-query","exec":"seq_main"}]',
        item: {
          type: "object",
          label: "路径映射",
          summaryFields: ["path", "exec"],
          fields: [
            {
              key: "path",
              description: "指定 DoH 请求路径。",
              label: "路径",
              type: "text",
              required: true,
              example: "/dns-query",
            },
            {
              key: "exec",
              description: "指定处理该路径请求的执行器。",
              label: "执行器",
              type: "reference",
              required: true,
              referenceTypes: ["executor"],
              referencePrefix: "",
              example: "seq_main",
            },
            {
              key: "json_api",
              description:
                "开启后，该路径的 GET 请求可使用 JSON DNS API 参数；RFC 8484 GET/POST 始终可用。",
              label: "JSON DNS API",
              type: "switch",
              default: false,
              advanced: true,
            },
          ],
        },
      },
      {
        key: "listen",
        description: "指定 HTTP/HTTPS 监听地址。",
        label: "监听地址",
        type: "text",
        example: ":443",
        required: true,
      },
      {
        key: "src_ip_header",
        description: "指定从请求头中读取真实客户端来源地址的字段名。",
        label: "来源 IP Header",
        type: "text",
        example: "X-Forwarded-For",
      },
      {
        key: "cert",
        description: "指定 HTTPS 证书文件路径。",
        label: "HTTPS 证书",
        type: "text",
        example: "/etc/oxidns/server.crt",
      },
      {
        key: "key",
        description: "指定 HTTPS 私钥文件路径。",
        label: "HTTPS 私钥",
        type: "text",
        example: "/etc/oxidns/server.key",
      },
      {
        key: "idle_timeout",
        description: "指定 HTTP 连接空闲超时。",
        label: "空闲超时(秒)",
        type: "number",
        default: 30,
        advanced: true,
      },
      {
        key: "enable_http3",
        description: "指定是否同时启用 HTTP/3。",
        label: "启用 HTTP/3",
        type: "switch",
        default: false,
        advanced: true,
      },
    ],
  },
  {
    kind: "quic_server",
    type: "server",
    name: "QUIC / DoQ Server",
    description: "DNS over QUIC 入口",
    icon: "Shield",
    metrics: serverMetrics,
    configSchema: [
      executorRef(
        "entry",
        "入口执行器",
        true,
        undefined,
        "指定 DoQ 请求进入策略链时使用的入口执行器。",
      ),
      {
        key: "listen",
        description: "指定 QUIC 监听地址。",
        label: "监听地址",
        type: "text",
        example: ":853",
        required: true,
      },
      {
        key: "cert",
        description: "指定 DoQ 所需 TLS 证书文件。",
        label: "TLS 证书",
        type: "text",
        example: "/etc/oxidns/server.crt",
        required: true,
      },
      {
        key: "key",
        description: "指定 DoQ 所需 TLS 私钥文件。",
        label: "TLS 私钥",
        type: "text",
        example: "/etc/oxidns/server.key",
        required: true,
      },
      {
        key: "idle_timeout",
        description: "指定 QUIC transport 的空闲超时。",
        label: "空闲超时(秒)",
        type: "number",
        advanced: true,
      },
    ],
  },
];
